baseURL = "https://pueblocolab.org/"  
languageCode = "en-us"
title = "Pueblo CoLab"
theme = "kube"
description = "Helping social innovators and small businesses around the world "
Paginate = 4
googleAnalytics = "'UA-144973086-1"
[Params]
  RSSLink = "/index.xml"
  author = "Pueblo CoLab" # add your company name
  github = "pueblocolab" # add your github profile name
  twitter = "pueblocolab" # add your twitter profile
  email = "hello@pueblocolab.org"

[[menu.main]]
    name = "Services"
    weight = -200
    url = "/services/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "About"
    weight = -300
    url = "/faq/"
